import { AvailableGenres } from '../anime/interface/anime-genres.interface';
import { AnimeGenreId } from '../jikan/interface/genre-sorted.interface';

export const GenreToIdMap: Record<AvailableGenres, number> = {
  [AvailableGenres.Action]: AnimeGenreId.Action,
  [AvailableGenres.Adventure]: AnimeGenreId.Adventure,
  [AvailableGenres.AwardWinning]: AnimeGenreId.AwardWinning,
  [AvailableGenres.Comedy]: AnimeGenreId.Comedy,
  [AvailableGenres.Drama]: AnimeGenreId.Drama,
  [AvailableGenres.Fantasy]: AnimeGenreId.Fantasy,
  [AvailableGenres.Gourmet]: AnimeGenreId.Gourmet,
  [AvailableGenres.Horror]: AnimeGenreId.Horror,
  [AvailableGenres.Mystery]: AnimeGenreId.Mystery,
  [AvailableGenres.Romance]: AnimeGenreId.Romance,
  [AvailableGenres.SciFi]: AnimeGenreId.SciFi,
  [AvailableGenres.SliceOfLife]: AnimeGenreId.SliceOfLife,
  [AvailableGenres.Sports]: AnimeGenreId.Sports,
  [AvailableGenres.Supernatural]: AnimeGenreId.Supernatural,
  [AvailableGenres.Suspense]: AnimeGenreId.Suspense,
  [AvailableGenres.Detective]: AnimeGenreId.Detective,
  [AvailableGenres.Educational]: AnimeGenreId.Educational,
  [AvailableGenres.Historical]: AnimeGenreId.Historical,
  [AvailableGenres.Isekai]: AnimeGenreId.Isekai,
  [AvailableGenres.MartialArts]: AnimeGenreId.MartialArts,
  [AvailableGenres.Mecha]: AnimeGenreId.Mecha,
  [AvailableGenres.Medical]: AnimeGenreId.Medical,
  [AvailableGenres.Military]: AnimeGenreId.Military,
  [AvailableGenres.Music]: AnimeGenreId.Music,
  [AvailableGenres.Mythology]: AnimeGenreId.Mythology,
  [AvailableGenres.Psychological]: AnimeGenreId.Psychological,
  [AvailableGenres.Racing]: AnimeGenreId.Racing,
  [AvailableGenres.Reincarnation]: AnimeGenreId.Reincarnation,
  [AvailableGenres.Samurai]: AnimeGenreId.Samurai,
  [AvailableGenres.School]: AnimeGenreId.School,
  [AvailableGenres.Space]: AnimeGenreId.Space,
  [AvailableGenres.Survival]: AnimeGenreId.Survival,
  [AvailableGenres.TimeTravel]: AnimeGenreId.TimeTravel,
  [AvailableGenres.Vampire]: AnimeGenreId.Vampire,
  [AvailableGenres.VideoGame]: AnimeGenreId.VideoGame,
  [AvailableGenres.Villainess]: AnimeGenreId.Villainess,
  [AvailableGenres.Josei]: AnimeGenreId.Josei,
  [AvailableGenres.Kids]: AnimeGenreId.Kids,
  [AvailableGenres.Seinen]: AnimeGenreId.Seinen,
  [AvailableGenres.Shoujo]: AnimeGenreId.Shoujo,
  [AvailableGenres.Shounen]: AnimeGenreId.Shounen,
};
